language: generic
sudo: required
# Promote to xenial when Travis fixes
# https://travis-ci.community/t/oracle-jdk-11-and-10-are-pre-installed-not-the-openjdk-builds/785/6
dist: trusty

env:
- PYENV_REHASH_TIMEOUT=120 RENV_PATHS_CACHE=$HOME/.cache/R/site-library

addons:
  apt:
    packages:
      - axel

before_install: ./travis/travis-setup.sh

install:
  - ./gradlew --console=plain --stacktrace check -x packratClean -x renvClean

scala:
  - 2.13.1

jdk:
  - openjdk8

python:
  - "2.7.10"

before_cache:
  - mkdir

cache:
  apt: true
  packages: true
  directories:
    - $HOME/.m2
    - $HOME/.cache
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/build/venv/lib
    - $HOME/.cache/R/site-library

notifications:
  email:
    - umayrh@gmail.com
