language: generic
sudo: false
dist: trusty

install:
  - ./gradlew check

scala:
  - 2.12.3

jdk:
  - oraclejdk8
  - openjdk8

addons:
  apt:
    sources:
    - r-packages-trusty
    packages:
    - r-base-dev

cache:
  directories:
    - /usr/local/lib/R/site-library
    - /usr/lib/R/site-library
    - /usr/lib/R/library

branches:
  only:
    - master
notifications:
  email:
    - umayrh@gmail.com
