language: generic
sudo: required
dist: trusty

before_install: ./travis/travis-setup.sh

install:
  - ./gradlew check

scala:
  - 2.12.3

jdk:
  - oraclejdk8
  - openjdk8

services:
  - neo4j

python:
  - "2.7"
  - "3.6.4"

cache:
  directories:
    - /usr/local/lib/R/site-library
    - /usr/lib/R/site-library
    - /usr/lib/R/library

branches:
  only:
    - master
notifications:
  email:
    - umayrh@gmail.com
