language: generic
sudo: required
dist: trusty

before_install: ./travis/travis-setup.sh

install:
  - ./gradlew check

scala:
  - 2.12.3

jdk:
  - oraclejdk8
  - openjdk8

python:
  - "2.7.10"
  - "3.6.4"

cache:
  apt: true
  directories:
    - $HOME/.m2
    - $HOME/.cache
    - $HOME/.cache/pip
    - $HOME/R/Library
    - $TRAVIS_BUILD_DIR/umayrh/sketchy-polytopes/R/*/packrat/lib
    - $TRAVIS_BUILD_DIR/umayrh/sketchy-polytopes/python/*/build/venv/lib

branches:
  only:
    - master
notifications:
  email:
    - umayrh@gmail.com
