language: generic
sudo: required
# Promote to xenial when Travis fixes
# https://travis-ci.community/t/oracle-jdk-11-and-10-are-pre-installed-not-the-openjdk-builds/785/6
dist: trusty

env:
- PYENV_REHASH_TIMEOUT=120

addons:
  apt:
    packages:
      - axel

before_install: ./travis/travis-setup.sh

install:
# TODO remove '-x document' after fixing devtools issue on Travis
  - ./gradlew --console=plain clean check -x packratClean -x renvClean

scala:
  - 2.13.1

jdk:
  - oraclejdk8
  - openjdk8

python:
  - "2.7.10"

cache:
  apt: true
  packages: true
  directories:
    - $HOME/.m2
    - $HOME/.cache
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
    - $TRAVIS_BUILD_DIR/build/venv/lib

branches:
  only:
    - master
notifications:
  email:
    - umayrh@gmail.com
