language: generic
sudo: required
dist: trusty

before_install: ./travis/travis-setup.sh

install:
  - ./gradlew check

scala:
  - 2.12.3

jdk:
  - oraclejdk8

python:
  - "2.7.10"

cache:
  apt: true
  directories:
    - $HOME/.m2
    - $HOME/.cache
    - $HOME/.cache/pip
    - /usr/lib/R/library
    - /usr/lib/R/site-library
    - /usr/local/lib/R/site-library
    - $TRAVIS_BUILD_DIR/umayrh/sketchy-polytopes/R/*/packrat/lib
    - $TRAVIS_BUILD_DIR/umayrh/sketchy-polytopes/python/*/build/venv/lib

before_cache:
    - mkdir -p /usr/lib/R/library && chmod 2777 /usr/lib/R/library
    - mkdir -p /usr/lib/R/site-library && chmod 2777 /usr/lib/R/site-library
    - mkdir -p /usr/local/lib/R/site-library && chmod 2777 /usr/local/lib/R/site-library

branches:
  only:
    - master
notifications:
  email:
    - umayrh@gmail.com
